### PR TITLE
415 refactor moves individual json

### LINKED ISSUE #415: Refactor to have moves in individual json files
This was at one point doen with the Pokemon json files.

Pros:
* It will be easier to spot errors when converting the source data
* It will be easier to find a specific move in the structure (not that it is hard now)
* There will be less data loaded at all times (not that it is that much data)
* The biggest factor is that it will be easier to maintain as giving the Pokemon json the same treatment have shown.

Cons:
* Harder to get an overview of all moves.

### PR DESCRIPTION
**Pull request by Jerakin**
Fixes #415 

Each move is now its own individual json file, this should help a lot when updating the data so we can easier see which move is being loaded. It should also be a tiny memory improvement as now we only have the used moves loaded

### CODE REVIEW

**Comment by Jerakin** [comment]
Just realized that you can't search to add moves now

**Comment by magroader** [comment]
I could definitely see the lack of a search being a problem.

Having the individual json files makes a lot of sense from a source control point of view - it's a lot easier to see what changed when you do an import, validate that the import didn't break things unintentionally, and that sort of thing. So I think that is valuable in itself. However, lack of search is bad.

What was the search doing before? Was it just searching names?

Some options... can you perhaps:
- Find all the names of the moves, assuming the file name is the same as the move name?
- Create an index of all the move names, and load that for searching purposes?

**Comment by Jerakin** [comment]
Finding all the names will be hard. I think it's probably better to export a `move_list.json` file and use that to search over. Will go with that

**Comment by magroader** [comment]
Yes, that's what I meant for my second bullet - your python process that outputs all the move json can also output a single index file.

I don't know how search indexing works, but in theory you could also make a much more robust index file that allows searching on more than just name. For example, "fire" to find all fire moves, or "push" to find any move that lets you push something.

**Comment by Jerakin** [comment]
I do like that. Though the data files doesn't know about things like that, so we would have to extend the data conversion. I think we should add a separate issue to extend the move search.

**Comment by Jerakin** [comment]
Sweet, this now works as it did before.

**Pull request merged**
